---
- hosts: localhost
  gather_facts: false

  tasks:
        - name: Get CPU usage
          shell: "top -b -n 1"
          register: top

        - name: Set CPU usage facts
          set_fact:
                        user_cpu: "{{top.stdout_lines[2].split()[1]}}"
                        system_cpu: "{{top.stdout_lines[2].split()[3]}}"

        - name: Output CPU usage facts
          debug:
                        msg:
                          - "User CPU usage: {{user_cpu}}"
                          - "System CPU usage: {{system_cpu}}"
        - name: hardware info
          vars:
            msg:
              RAM:{{ansible_memtotal_mb}}
          SWAP: {{ansible_memory_mb.swap.total}}
          debug:
           msg: "{{msg.split('\n')}}"
